### ISSUE TITLE
Implement transaction class

### ISSUE THREAD

**Issue by chinghanyu** [chinghanyu/BHNVGCBalanceChecker#4]
We might need to create a class `Transaction` that help hold each transaction and we simply print out transactions on each card.

We use the class constructor to parse the transaction message, so all `main()` function need to do are:
1. to parse `response.text`
2. find out HTML tags that hold card transactions
3. feed each transaction to the class constructor of `Transaction` class.
4. print out the card transactions in a formatted way

**Comment by earlyshen** [comment]
Maybe some existing HTML parser will help:

- https://www.crummy.com/software/BeautifulSoup/bs4/doc/
- https://docs.python.org/2.7/library/htmlparser.html?highlight=html

**Comment by chinghanyu** [comment]
I believe `htmlparser` is enough. We can use that one to extract transactions through tag searching.

**Comment by earlyshen** [comment]
Addressed in https://github.com/chinghanyu/BHNVGCBalanceChecker/pull/10
