### ISSUE TITLE
GCMall Website Update

### ISSUE THREAD

**Issue by earlyshen** [chinghanyu/BHNVGCBalanceChecker#5]
GCMall change their sites on 1/27/2017, which makes the whole script failed. 
Attached Charles log: [GCMall.chls.zip](https://github.com/chinghanyu/BHNVGCBalanceChecker/files/734658/GCMall.chls.zip)

We might need to:
1. Add `X-Requested-With=XMLHttpRequest` to POST request
2. Change the GET request url to `_CardTransactions`

**Comment by chinghanyu** [comment]
Accommodated.
